Es6
dieum512/Awesome-books-with-ES6 pull request #1
Opened 2023-01-18 08:32 UTC by dieum512

In this branch I:

- Created the HTML, CSS, and JS files
- Divided the JS file into some modules
- Updated the README file and 
- Checked for and corrected some linter errors

2023-01-18 09:03 UTC, muneebulrehman requested changes
Hi @dieum512 , 

Good job so far! I see you put a lot of effort into this project. However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- No linter errors
- Descriptive PR
- Good docs

## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly rename your `script.js` file to `index.js`. It is one of the project requirements and also a convention in the JS world. The main file is generally named as `index.js`.⬇️
![image](https://user-images.githubusercontent.com/33268927/213128965-0b8a72df-364d-4d92-b922-601a3403d0a0.png)


- [ ] Kindly move all the modules you have created to the `modules` directory. It is one of the project requirements. This will help you keep the project clean and you know what files are where. ⬇️
![image](https://user-images.githubusercontent.com/33268927/213128764-7b1a35c2-4480-440b-89a5-976beb142021.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-18 09:03 UTC, muneebulrehman commented on UI.js
> +  static displayBooks() {
kindly use the arrow functions as per the requirements of the project. ⬇️
![image](https://user-images.githubusercontent.com/33268927/213127048-5db65375-37e8-4836-bcc0-1a978b598e31.png)

2023-01-18 09:03 UTC, muneebulrehman commented on UI.js
> +  static addBook(book) {
kindly use the arrow functions as per the requirements of the project. ⬇️
![image](https://user-images.githubusercontent.com/33268927/213127048-5db65375-37e8-4836-bcc0-1a978b598e31.png)

2023-01-18 09:03 UTC, muneebulrehman commented on UI.js
> +  static deleteBook(el) {
kindly use the arrow functions as per the requirements of the project. ⬇️
![image](https://user-images.githubusercontent.com/33268927/213127048-5db65375-37e8-4836-bcc0-1a978b598e31.png)

2023-01-18 09:03 UTC, muneebulrehman commented on UI.js
> +  static clearFields() {
kindly use the arrow functions as per the requirements of the project. ⬇️
![image](https://user-images.githubusercontent.com/33268927/213127048-5db65375-37e8-4836-bcc0-1a978b598e31.png)

2023-01-18 09:03 UTC, muneebulrehman commented on store.js
> +  static getBooks() {
kindly use the arrow functions as per the requirements of the project. ⬇️
![image](https://user-images.githubusercontent.com/33268927/213127048-5db65375-37e8-4836-bcc0-1a978b598e31.png)

2023-01-18 09:03 UTC, muneebulrehman commented on store.js
> +  static addBook(book) {
kindly use the arrow functions as per the requirements of the project. ⬇️
![image](https://user-images.githubusercontent.com/33268927/213127048-5db65375-37e8-4836-bcc0-1a978b598e31.png)

2023-01-18 09:03 UTC, muneebulrehman commented on store.js
> +  static removBook(title) {
kindly use the arrow functions as per the requirements of the project. ⬇️
![image](https://user-images.githubusercontent.com/33268927/213127048-5db65375-37e8-4836-bcc0-1a978b598e31.png)

2023-01-18 10:32 UTC, KayLemba requested changes
Hi @dieum512    👋
Good job so far working on the project requirements!
There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight 🎉
No linter errors. ✔️
GitHub flow is followed. ✔️

Required Changes ♻️
Check the comments under the review in the inline comments.

Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-01-18 10:32 UTC, KayLemba commented on modules/UI.js
> +      el.parentElement.parentElement.remove();
As suggested by the previous code reviewer  You need to display the current date below the navigation bar, and for this, you need to use the Luxon library. Kindly go through project requirements and implement this feature.

2023-01-18 10:32 UTC, KayLemba commented on style.css
> +  /* margin-top: 1000px; */
Please kindly get rid of unused code for it makes your code base look untidy.

2023-01-19 12:41 UTC, Omar-Muhamad approved these changes
# Approved ✔
### Hi @dieum512,

Great job, Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![thumbs-up-agree](https://user-images.githubusercontent.com/68796232/158491866-20000001-88c2-4735-bb47-1ff65c7a44db.gif)


## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used the correct workflow.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- N/A

## [Optional] suggestions:

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-01-19 12:42 UTC, merged